spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gather}
    username: ${SPRING_DATASOURCE_USERNAME:hussain.sw}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

server:
  port: ${SERVER_PORT:8080}

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
